[project]
name = "PlexAniBridge-Mappings"
version = "2.1"
description = "PlexAniBridge mappings repository with automated aggregation, validation, and manual curation."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }

authors = [
    { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" }
]
maintainers = [
    { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" },
    { name = "LuceoEtzio" }
]

dependencies = [
    "gitpython>=3.1.45",
    "lxml>=6.0.2",
    "pydantic>=2.12.3",
    "requests>=2.32.5",
    "ruamel-yaml>=0.18.16",
]

[project.urls]
Homepage = "https://plexanibridge.elias.eu.org"
Documentation = "https://plexanibridge.elias.eu.org"
Source = "https://github.com/eliasbenb/PlexAniBridge-Mappings"
Issues = "https://github.com/eliasbenb/PlexAniBridge-Mappings/issues"

[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["B", "D", "DOC", "E", "F", "I", "RUF", "SIM", "UP", "W"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
