[project]
name = "plexanibridge-mappings"
version = "3.0.0"
description = "PlexAniBridge Mappings Aggregator"
readme = "README.md"
requires-python = ">=3.13"

authors = [
    { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" }
]
maintainers = [
    { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" },
    { name = "LuceoEtzio" }
]

dependencies = [
    "gitpython>=3.1.44",
    "lxml>=6.0.0",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
    "ruamel-yaml>=0.18.14",
]

[project.urls]
Homepage = "https://plexanibridge.elias.eu.org"
Documentation = "https://plexanibridge.elias.eu.org"
Source = "https://github.com/eliasbenb/PlexAniBridge-Mappings"
Issues = "https://github.com/eliasbenb/PlexAniBridge-Mappings/issues"

[tool.pyright]
include = ["update_mappings.py"]

[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "scripts/**/*.py"]
indent-width = 4
line-length = 88

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "D", "RUF"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Body",
    "fastapi.Cookie",
    "fastapi.Depends",
    "fastapi.File",
    "fastapi.Form",
    "fastapi.Header",
    "fastapi.Path",
    "fastapi.Query",
    "fastapi.Security",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
