name: Update Mappings

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
      - 'data/**'
      - 'mappings.edits.yaml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'update_mappings.py'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%B %d, %Y %I:%M %p')" >> $GITHUB_OUTPUT

      - name: Check Out Repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --no-dev --no-editable --python=3.13

      - name: Run Update Anime IDs
        run: uv run python update_mappings.py

      - name: Display Problems Report
        run: |
          cat problems.md >> $GITHUB_STEP_SUMMARY

      - name: Generate Git Diff
        run: |
          git diff . > git_diff.txt
          echo "## Git Diff" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          cat git_diff.txt >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check Diff
        id: verify_diff
        run: |
          git diff .
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push Changes
        if: steps.verify_diff.outputs.changed == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Mappings updated at ${{ steps.date.outputs.date }} UTC" -a
          git push
